version: "3.7"

services:
  nginx:
    image: nginx
    container_name: "dictation_nginx"
    restart: always
    working_dir: /var/www/html
    ports:
      - "7894:80"
    volumes:
      - .:/var/www/html
      - ./.docker/nginx:/etc/nginx/conf.d

  web:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    container_name: "dictation_php"
    restart: always
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./.docker/php/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  db:
    image: mysql
    container_name: "dictation_db"
    restart: always
    volumes:
      - .db:/var/lib/mysql
      - ./storage/app:/var/export
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
